version: '3.3'

services:
  postgres: 
    image: postgres:13.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: windr
      POSTGRES_DB: windr
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    ports:
      - "1337:1337"
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile.dev
    depends_on:
      - server
    ports:
      - "3000:3000"