version: '1'

services:
  postgres: 
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    image: strapi/strapi:v3.6.8
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - STRAPI_URL=http://server:3000
      - STRAPI_SECRET=mysecret
      - STRAPI_ADMIN_PASSWORD=admin
      - STRAPI_ADMIN_USERNAME=admin
  app:
    image: nodejs:14.16.1-alpine
    depends_on:
      - server
    ports:
      - "3000:3000"
    command: npm start
