runtime: nodejs14

# 512 MB	1.2 GHz	manual, basic
instance_class: B2 

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: '04tfdoP8gvavtln6'
  DATABASE_NAME: 'strapi'
  DATABASE_MIN_CONNECTIONS: 5
  INSTANCE_CONNECTION_NAME: 'robotic-charmer-327516:us-central1:strapi-production'
  STORAGE_BUCKET_NAME: 'windr-sites-uploads'
beta_settings:
  cloud_sql_instances: 'robotic-charmer-327516:us-central1:strapi-production'
