name: Deploy Backend to Google App Engine
on:
  push:
    branches:
      - master
    paths:
      - "backend/**"

jobs:
  build-and-deploy-to-gae:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-cloudrun@v0
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run deploy
