name: Deploy Backend to Google App Engine
on:
  push:
    branches:
      - master
    paths:
      - "backend/**"

jobs:
  build-and-deploy-to-gae:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Set up Cloud SDK and Authenticate
        uses: google-github-actions/setup-gcloud@v0
      - uses: google-github-actions/auth@v0
        with:
           credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Deploy
        run: npm run deploy
